# Generated by Django 3.0.5 on 2020-05-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200411_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
