# Generated by Django 3.0.5 on 2020-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200505_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='num_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='num_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='sq_footage',
            field=models.IntegerField(),
        ),
    ]
