# Generated by Django 3.0.5 on 2020-05-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_property_model_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_model',
            name='picture',
        ),
    ]
