# Generated by Django 3.0.5 on 2020-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_property_model_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='upload',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
