# Generated by Django 3.0.3 on 2020-05-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_auto_20200514_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_model',
            name='applicant',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_model',
            name='property',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='myapp.Property_Model'),
            preserve_default=False,
        ),
    ]
