# Generated by Django 3.0.3 on 2020-04-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_property_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion_model',
            name='author',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='Suggestion_Model',
        ),
    ]
