# Generated by Django 3.0.5 on 2020-05-06 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200505_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_model',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
