# Generated by Django 3.0.5 on 2020-05-06 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_property_model_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_model',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
